name: server CD

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'packages/common/**'
      - 'packages/server/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      !contains( github.event.pull_request.labels.*.name, 'NO-DEPLOY')

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "quiet-time"
          heroku_email: "bepyan@naver.com"
